[book]
title = "psvm203"
authors = ["psvm203"]
description = "psvm203의 블로그"
language = "ko"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/psvm203/psvm203.github.io"

[output.html.print]
enable = false
