[book]
title = "psvm203"
authors = ["psvm203"]
description = "psvm203의 블로그"
language = "ko"

[rust]
edition = "2021"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
mathjax-support = true
no-section-label = true
additional-css = ["./theme/css/catppuccin.css", "./theme/css/custom.css"]
git-repository-url = "https://github.com/psvm203/psvm203.github.io"

[output.html.print]
enable = false
